num_epochs: 100
mode: 2 #0 for both t1 and t2 , 1 for t1 only , 2 for t2 only
path_to_data: '/home/GRAMES.POLYMTL.CA/luroub/luroub_local/lurou_local/deep_VL_2019/straight/'
saved_model: 'checkpoints/Countception_L2T2.model' # leave '' will use a default value 
previous_weights: 'checkpoints/Countception_L2T2.model' #Leave '' if you don't want to load , or don't have previous weights
