weights: 'checkpoints/Countception_c2.model' #Path to weights to use for the test
mode: 2 # if 1 test will only use T1 , if 2 test will only use T2, if 0 test will use T1 and T2 
path_to_data: '/home/GRAMES.POLYMTL.CA/luroub/luroub_local/lurou_local/deep_VL_2019/straight/' # path to image data in Bids format
c2_or_full: 'c2' # Use C2 to only load C2/C3 disc in GT. Use 'full' to use all of them. 
